//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BakhtinExan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказы
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Заказы()
        {
            this.СоставЗаказа = new HashSet<СоставЗаказа>();
        }
    
        public int ID { get; set; }
        public Nullable<int> СатутсID { get; set; }
        public Nullable<System.DateTime> ДатаПоставки { get; set; }
        public Nullable<int> ПунктВыдачиID { get; set; }
        public Nullable<System.DateTime> ДатаЗаказа { get; set; }
        public Nullable<int> КлиентID { get; set; }
        public Nullable<int> КодДляПолучения { get; set; }
    
        public virtual Пользователи Пользователи { get; set; }
        public virtual ПунктыВыдачи ПунктыВыдачи { get; set; }
        public virtual Статусы Статусы { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<СоставЗаказа> СоставЗаказа { get; set; }
    }
}
