//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BakhtinExan
{
    using System;
    using System.Collections.Generic;
    
    public partial class СоставЗаказа
    {
        public int ID { get; set; }
        public Nullable<int> ЗаказID { get; set; }
        public string ТоварID { get; set; }
        public Nullable<int> КолВо { get; set; }
    
        public virtual Заказы Заказы { get; set; }
    }
}
